# Generated by Django 5.0.1 on 2024-02-01 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="category",
        ),
    ]
