# Generated by Django 5.0.1 on 2024-02-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_remove_content_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
