# Generated by Django 5.0.1 on 2024-02-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0003_content_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
