# Generated by Django 5.0.1 on 2024-02-07 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="mobile_number",
        ),
    ]
